northwind_shop:
 target: dev
 outputs:
    dev:
        type: bigquery
        method: service-account
        keyfile: C:\Users\user\Downloads\dbt-user.json
        project: projeto-teste-291214
        dataset: dbt_leonardo
        threads: 1
        timeout_seconds: 300
        location: US
        priority: interactive