northwind_shop:
 target: dev
 outputs:
    dev:
        type: bigquery
        method: service-account
        keyfile: projprojeto-teste-291214-fb2d5b26358b.json
        project: projeto-teste-291214
        dataset: dbt_leonardo
        threads: 1
        timeout_seconds: 300
        location: US
        priority: interactive